### ISSUE TITLE
ERROR : Call to undefined method App\ApiJson\Model\MysqlQuery::insertGetId()

### ISSUE THREAD

**Issue by lbgxcn** [kvnZero/hyperf-APIJSON#24]
@kvnZero 你好，我刚刚接触到这个项目，测试中碰到一个问题。
1.我按照下面的步骤，拉起了docker

docker build -t hyperf-apijson:v1 .
#启动容器 映射本地9501端口
docker run -dit --name hyperf-apijson -p 9501:9501 hyperf-apijson:v1

2.测试get接口成功
![截图 2024-06-25 15-05-43](https://github.com/kvnZero/hyperf-APIJSON/assets/155232007/39fe6415-7814-442d-8fbd-bfbdf29bd629)

3.测试post接口时，提示这个insertGetId的错误
[
![截图 2024-06-25 15-25-27](https://github.com/kvnZero/hyperf-APIJSON/assets/155232007/b88161da-5f16-438b-b591-99b5aaff79d5)
](url)
![截图 2024-06-25 15-26-44](https://github.com/kvnZero/hyperf-APIJSON/assets/155232007/fa4be6e3-71fb-43bb-974a-2f23764e0f0e)

curl的测试脚本如下：
curl -X POST http://localhost:19501/post -H 'Content-Type: application/json' -d '{"Finstmts":{"clientguid":"246","fs_type":"2","fs_date":"2","create_at":"2","create_by":"2","file_id":"234"}}'|jq

4.我也尝试将id字段改成 Id, finstmtsID，还是一样的问题。

麻烦看看是什么地方有问题？非常感谢！

**Comment by kvnZero** [comment]
#25 在批量Insert方法时遗漏修改
